/* Generated by Yosys 0.25 (git sha1 e02b7f64bc7, gcc 13.1.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* \amaranth.hierarchy  = "tt_sup3legacy_trng" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module tt_sup3legacy_trng(uo_out, uio_in, uio_out, uio_oe, clk, ena, rst_n, ui_in);
  reg \$auto$verilog_backend.cc:2083:dump_module$3  = 0;
  wire [6:0] \$2 ;
  wire [6:0] \$3 ;
  wire [4:0] \$5 ;
  wire [7:0] \$7 ;
  input clk;
  wire clk;
  wire \clk$1 ;
  input ena;
  wire ena;
  reg [5:0] o = 6'h00;
  reg [5:0] \o$next ;
  reg [5:0] q = 6'h00;
  reg [5:0] \q$next ;
  wire rst;
  input rst_n;
  wire rst_n;
  input [7:0] ui_in;
  wire [7:0] ui_in;
  input [7:0] uio_in;
  wire [7:0] uio_in;
  input [7:0] uio_oe;
  wire [7:0] uio_oe;
  input [7:0] uio_out;
  wire [7:0] uio_out;
  output [7:0] uo_out;
  wire [7:0] uo_out;
  assign \$3  = q + 1'h1;
  assign \$5  = q[5:1] ^ q[4:0];
  assign \$7  = + o;
  always @(posedge \clk$1 )
    o <= \o$next ;
  always @(posedge \clk$1 )
    q <= \q$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \q$next  = \$3 [5:0];
    casez (rst)
      1'h1:
          \q$next  = 6'h00;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \o$next  = { q[5], \$5  };
    casez (rst)
      1'h1:
          \o$next  = 6'h00;
    endcase
  end
  assign \$2  = \$3 ;
  assign uo_out = \$7 ;
  assign rst = rst_n;
  assign \clk$1  = clk;
endmodule
